name: location_marker
description: "地点标记 App —— UI Demo（仅页面设计，无功能实现）"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
